name: Release to Cloud Run

on:
  push:
    branches:
      - main

env:
  GOOGLE_CLOUD_REGION: "asia-northeast1"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Test
        run: |
          python --version

      - name: Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDP }}
          service_account: "sa-cicd@${{ secrets.GOOGLE_CLOUD_PROJECT }}.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure docker
        run: gcloud auth configure-docker ${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: "build"
        uses: docker/build-push-action@v5
        with:
          context: ./server/src
          tags: ${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/apps/server:${{ github.sha }}
          push: true

      - id: "deploy"
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: app
          region: ${{ env.GOOGLE_CLOUD_REGION }}
          image: ${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/my-apps/streamlit:${{ github.sha }}
          flags: --service-account=sa-app@${{ secrets.GOOGLE_CLOUD_PROJECT }}.iam.gserviceaccount.com
          env_vars: |
            PROJECT_ID=${{ secrets.GOOGLE_CLOUD_PROJECT }}
