name: Release to Cloud Run

on:
  push:
    branches:
      - main

env:
  GOOGLE_CLOUD_REGION: "asia-northeast1"

jobs:
  test-client:
    name: Test clients
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Lint
        run: |
          python -m pip install requests flake8 isort black
          python -m flake8 --exclude=.venv --extend-ignore=E203,E402 --max-line-length=120 --show-source .
        working-directory: client

  release-client:
    name: Release clients
    runs-on: ubuntu-latest
    needs: test-client

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDP }}
          service_account: "sa-cicd@${{ secrets.GOOGLE_CLOUD_PROJECT }}.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure docker
        run: gcloud auth configure-docker ${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get short SHA
        run: echo "SHORT_SHA=$(echo "${{ github.sha }}" | cut -c 1-7)" >> $GITHUB_ENV

      - id: "build-001"
        uses: docker/build-push-action@v5
        with:
          context: ./client
          tags: ${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/apps/client-001:${{ env.SHORT_SHA }}
          build-args: CLIENT=001
          push: true

      - id: "build-002"
        uses: docker/build-push-action@v5
        with:
          context: ./client
          tags: ${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/apps/client-002:${{ env.SHORT_SHA }}
          build-args: CLIENT=002
          push: true

  release-server:
    name: Release API server
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDP }}
          service_account: "sa-cicd@${{ secrets.GOOGLE_CLOUD_PROJECT }}.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure docker
        run: gcloud auth configure-docker ${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get short SHA
        run: echo "SHORT_SHA=$(echo "${{ github.sha }}" | cut -c 1-7)" >> $GITHUB_ENV

      - id: "build"
        uses: docker/build-push-action@v5
        with:
          context: ./server/src
          tags: ${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/apps/server:${{ env.SHORT_SHA }}
          push: true

      - id: "deploy"
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: app
          region: ${{ env.GOOGLE_CLOUD_REGION }}
          image: ${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/apps/server:${{ env.SHORT_SHA }}
          flags: --service-account=sa-app@${{ secrets.GOOGLE_CLOUD_PROJECT }}.iam.gserviceaccount.com --cpu=0.1 --memory=128Mi --concurrency=1 --max-instances=10 --no-allow-unauthenticated
          env_vars: |
            PROJECT_ID=${{ secrets.GOOGLE_CLOUD_PROJECT }}
